server:
  port: 9137
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datajpa
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true